--DATA BASE MYSQL
CREATE DATABASE IF NOT EXISTS `Central Bank` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

USE `Central Bank`;

-- Table structure for table Centrals
CREATE TABLE CENTRALS (
    ID_CENTRAL INT NOT NULL AUTO_INCREMENT,
    NAME_CENTRAL VARCHAR(50) NOT NULL,
    ADDRESS_CENTRAL VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID_CENTRAL)
);

-- Table structure for table Branch IS A RELATIONSHIP WITH CENTRALS
CREATE TABLE BRANCHS (
    ID_BRANCH INT NOT NULL AUTO_INCREMENT,
    NAME_BRANCH VARCHAR(50) NOT NULL,
    ADDRESS_BRANCH VARCHAR(50) NOT NULL,
    ID_CENTRAL_BRANCH INT NOT NULL,
    PRIMARY KEY (ID_BRANCH),
    FOREIGN KEY (ID_CENTRAL) REFERENCES CENTRALS(ID_CENTRAL)
);


